### ISSUE TITLE
Auto-Genetate Schemas.

### ISSUE THREAD

**Issue by DNature** [CombatCovid/backend-hardware-designs-registry#10]
I was working on this project recently and @raahul1912 has done a lot. However, i think it's gonna be better to generate and merge schemas on the fly by scanning through the components directory for every file that ends with an extension type - i.e `*.graphql` then we wont have to bother about importing and adding a new schema into our array of schemas. there're a lot of tools to archive this. 

i.e with [merge-graphql-schemas](https://github.com/Urigo/merge-graphql-schemas) and few other tools:
```js
import { mergeResolvers, mergeTypes } from 'merge-graphql-schemas';
...

export const genSchema = (): GraphQLSchema => {
  const pathComponents = path.join(__dirname, '../components');
  const graphqlTypes = glob.sync(`${pathComponents}/**/*.graphql`).map((x) => fs.readFileSync(x, { encoding: 'utf8' }));

  const resolvers = glob.sync(`${pathComponents}/**/resolvers.?s`).map((resolver) => require(resolver).resolvers);

  return makeExecutableSchema({
    typeDefs: mergeTypes(graphqlTypes),
    resolvers: mergeResolvers(resolvers)
  });
};
```

The above code will save scale better than this though i've been using the array method.
```js
const schema: GraphQLSchema = makeExecutableSchema({
  typeDefs: [postTypeDef, userTypeDef, commentsTypeDefs, ...],
  resolvers: [postResolvers, userResolvers, commentsResolvers, ...]
});
```

**Comment by raahul1912** [comment]
@DNature you are right. I have tried this earlier but unfortunately not got success.

**Comment by DNature** [comment]
Alright. I got it to work.

How about generating namespaces for mutations to prevent using type any on every mutation argument?
